##################  Add, Edit, buy, sell, LTH, Pla/Pause APIs  ####################

###

POST http://34.205.124.51:3010/apiEndPoint/createManualOrder
Content-Type: application/json

{ "orderArr": {
        "admin_id": "5c0912bffc9aadaac61dd074",
        "application_mode": "test",
        "auto_sell": "yes",
        "buy_trail_percentage": 0.1, 
        "buy_trail_price": "0.00000013", 
        "exchange": "binance",
        "lth_functionality": "yes", 
        "lth_profit": 15.3, 
        "order_type": "market_order",
        "price":1.3e-7,
        "quantity": 2222,
        "sell_price":1.43e-7,  - conditional
        "status": "new",
        "symbol": "NCASHBTC",
        "trail_check": "yes", 
        "trail_interval": "0.00000000", 
        "trigger_type": "no"
    },
    "tempOrderArr": {
        "admin_id": "5c0912bffc9aadaac61dd074",
        "application_mode": "test",
        "iniatial_trail_stop":1.1895e-7,
        "loss_percentage": 8.5,
        "lth_functionality": "yes",
        "lth_profit": 15.3,
        "order_type": "market_order",
        "profit_percent": 10,
        "profit_price":1.43e-7,
        "profit_type": "percentage",
        "sell_trail_percentage": 0.2,
        "stop_loss": "yes",
        "trail_check": "yes",
        "trail_interval":2.6000000000000003e-10
    }
}

###

POST http://34.205.124.51:3010/apiEndPoint/updateManualOrder
Content-Type: application/json

{   "exchange": "binance",
    "buyOrderId": "5dd63766588ade0019f03168",
    "orderArr": {
        "activate_stop_loss_profit_percentage": 100,
        "custom_stop_loss_percentage": 3.5,
        "defined_sell_percentage": 1.774,
        "exchange": "binance",
        "iniatial_trail_stop": 0.0005231265,
        "iniatial_trail_stop_copy": 0.0005231265,
        "lth_functionality": "yes",
        "lth_profit": 4.6,
        "orderId": "5ddb9e993c63ec2698430902",
        "sell_profit_percent": 1.774,
        "stop_loss_rule": "custom_stop_loss",
        "un_limit_child_orders": "no"
    },
    "sellOrderId": "5df84dd6052c7f78fb42abd7",
    "sellOrderArr": {
        "iniatial_trail_stop": 0.000028660499999999998,
        "loss_percentage": "1.00",
        "lth_functionality": "yes",
        "lth_profit": 11.8,
        "profit_type": "percentage",
        "sell_price": 0.000029229400000000002,
        "sell_profit_percent": "1.00",
        "sell_trail_percentage": 0.1,
        "stop_loss": "yes",
        "trail_check": "yes",
        "trail_interval": 2.895e-8
    },
    "tempSellOrderId": ""
}

###

POST http://34.205.124.51:3010/apiEndPoint/createAutoOrder
Content-Type: application/json

{ "orderArr": {
        "activate_stop_loss_profit_percentage": 100,
        "admin_id": "5c0912bffc9aadaac61dd074",
        "application_mode": "test",
        "current_market_price": "0.00102040",
        "custom_stop_loss_percentage": 5.5,
        "defined_sell_percentage": 5.2,
        "exchange": "binance",
        "lth_functionality": "yes",
        "lth_profit": 10.7,
        "market_value": "",
        "order_level": "level_15",
        "order_mode": "test",
        "order_type": "market_order",
        "parent_status": "parent",
        "pause_status": "play",
        "price": "",
        "quantity": 0.3,
        "sell_profit_percent": 5.2,
        "status": "new",
        "stop_loss_rule": "custom_stop_loss",
        "symbol": "ZENBTC",
        "trigger_type": "barrier_percentile_trigger",
        "un_limit_child_orders": "no"
    }
}

###

POST http://34.205.124.51:3010/apiEndPoint/editAutoOrder
Content-Type: application/json

{ "orderArr": {
        "activate_stop_loss_profit_percentage": 100,
        "custom_stop_loss_percentage": 3.5,
        "defined_sell_percentage": 1.774,
        "exchange": "binance",
        "iniatial_trail_stop": 0.0005231265,
        "iniatial_trail_stop_copy": 0.0005231265,
        "lth_functionality": "yes",
        "lth_profit": 4.6,
        "orderId": "5ddb9e993c63ec2698430902",
        "sell_profit_percent": 1.774,
        "stop_loss_rule": "custom_stop_loss",
        "un_limit_child_orders": "no"
    }
}

###

POST http://34.205.124.51:3010/apiEndPoint/buyOrderManually
Content-Type: application/json

{ 
    "coin": "NEOBTC",
    "exchange": "binance",
    "orderId": "5df334958cff810019b21908"
}

###

POST http://34.205.124.51:3010/apiEndPoint/sellOrderManually
Content-Type: application/json

{ 
    "currentMarketPriceByCoin": "0.00053440",
    "definedSellPrice": 0.0005355,
    "exchange": "binance",
    "orderId": "5ddb9e993c63ec2698430902"
}

###

POST http://34.205.124.51:3010/apiEndPoint/orderMoveToLth
Content-Type: application/json

{ 
    "exchange": "binance",
    "lth_profit": 56,
    "orderId": "5df7a4cd28981a0019c6e843"
}

###

POST http://34.205.124.51:3010/apiEndPoint/togglePausePlayOrder

###


#################  New Global APIS  ##############

POST http://34.205.124.51:3010/apiEndPoint/createManualOrderGlobally
Content-Type: application/json

{ "orderArr": {
        "admin_id": "5c0912bffc9aadaac61dd074",
        "application_mode": "test",
        "auto_sell": "yes",
        "buy_trail_percentage": 0.1,
        "buy_trail_price": "0.00000013",
        "exchange": "binance",
        "lth_functionality": "yes",
        "lth_profit": 15.3,
        "order_type": "market_order",
        "price":1.3e-7,
        "quantity": 2222,
        "sell_price":1.43e-7,
        "status": "new",
        "symbol": "NCASHBTC",
        "trail_check": "yes",
        "trail_interval": "0.00000000",
        "trigger_type": "no"
    },
    "tempOrderArr": {
        "admin_id": "5c0912bffc9aadaac61dd074",
        "application_mode": "test",
        "iniatial_trail_stop":1.1895e-7,
        "loss_percentage": 8.5,
        "lth_functionality": "yes",
        "lth_profit": 15.3,
        "order_type": "market_order",
        "profit_percent": 10,
        "profit_price":1.43e-7,
        "profit_type": "percentage",
        "sell_trail_percentage": 0.2,
        "stop_loss": "yes",
        "trail_check": "yes",
        "trail_interval":2.6000000000000003e-10
    }
}


###

# POST http://localhost:3010/apiEndPoint/getTradeBuyLimitCheck
POST http://34.205.124.51:3010/apiEndPoint/getTradeBuyLimitCheck
Content-Type: application/json

{ 
    "exchange": "binance",
    "user_id": "5c0912b7fc9aadaac61dd072",
    "usd_worth": 50
}

###

POST http://localhost:3010/apiEndPoint/get_user_id
# POST http://34.205.124.51:3010/apiEndPoint/get_user_id
Content-Type: application/json

{ 
    "username": "admin"
}

###

# POST http://localhost:3010/apiEndPoint/hit_auto_buy_cron
POST http://34.205.124.51:3010/apiEndPoint/hit_auto_buy_cron
Content-Type: application/json

{ 
    "user_id": "",
    "exchange": "binance"
}


###

GET http://localhost:3010/apiEndPoint/myTest2
# GET http://34.205.124.51:3010/apiEndPoint/myTest2
###

GET http://localhost:3010/apiEndPoint/test_code
# GET http://34.205.124.51:3010/apiEndPoint/test_code
###

GET http://localhost:3010/apiEndPoint/test_test
# GET http://34.205.124.51:3010/apiEndPoint/test_code

###

GET http://localhost:3010/apiEndPoint/deleteLogsTest
# GET http://34.205.124.51:3010/apiEndPoint/deleteLogsTest

###

GET http://localhost:3010/apiEndPoint/test_internal_function
# GET http://34.205.124.51:3010/apiEndPoint/test_internal_function



###

POST http://localhost:3010/apiEndPoint/updateDailyActualTradeAbleAutoTradeGen
# POST http://34.205.124.51:3010/apiEndPoint/updateDailyActualTradeAbleAutoTradeGen
Content-Type: application/json

{ 
    "user_id": "5c0912b7fc9aadaac61dd072",
    "exchange": "binance"
}

###

POST http://localhost:3010/apiEndPoint/is_trade_limit_exceeded
# POST http://34.205.124.51:3010/apiEndPoint/is_trade_limit_exceeded
Content-Type: application/json

{
    "user_id": "5c86f33bfc9aad989b4ca8d2",
    "exchange": "kraken"
}

###

POST http://localhost:3010/apiEndPoint/updateDailyTradeSettings_digie
# POST http://34.205.124.51:3010/apiEndPoint/updateDailyTradeSettings_digie
Content-Type: application/json

{ 
    "user_id": "5c0913a0fc9aadaac61dd0be",
    "exchange": "binance",
    "application_mode": "live"
}

###

POST http://localhost:3010/apiEndPoint/is_trading_points_exceeded
# POST http://34.205.124.51:3010/apiEndPoint/is_trading_points_exceeded
Content-Type: application/json

{ 
    "user_id": "5eb5a5a628914a45246bacc6"
}

###

###

POST http://localhost:3010/apiEndPoint/test_user_api_key
# POST http://34.205.124.51:3010/apiEndPoint/test_user_api_key
Content-Type: application/json

{ 
    "user_id": "5c09134cfc9aadaac61dd09c"
}


###

POST http://34.199.235.34:3200/updateUserBalance
Content-Type: application/json

{ 
    "user_id": "5c0912b7fc9aadaac61dd072",
    "validating": true,
    "api_key": "lKe4YhcP9p6A2TgaWizyLRnXr1c/bfImVrXaezwgm0In5ad5JPxWUfaZ",
    "api_secret": "yFMACoiyIKulnfcEOvPOtYjbidCKhhzK4+xHfqjnfLezR02Jo1sHOgj9PHkwCBiMHG7Pm5MJLKeMY5GS++9g+w=="
}

###

POST https://users.digiebot.com/cronjob/GetUserTotalPoints
Content-Type: application/json
Authorization: Basic cG9pbnRTdXBwbHk6NGU0NmQ5OWFjMjJhNGIwYWJlNTc2OGE3OGVlODdiOGM=

{ 
    "user_id": "5eb5a5a628914a45246bacc6"
}


###

POST http://52.22.53.12:3600/buySellPostBAM
Content-Type: application/json

{ 
    "user_id": "5c0912b7fc9aadaac61dd072",
    "symbol": "BTCUSDT",
    "quantity": 0.000522,
    "exchange": "bam",
    "action": "sell"
}

###

POST http://52.22.53.12:3600/buySellPostBAM
Content-Type: application/json

{ 
    "user_id": "5c0912b7fc9aadaac61dd072",
    "symbol": "LTCUSDT",
    "quantity": 0.14221,
    "exchange": "bam",
    "action": "sell"
}

###

POST http://localhost:3010/apiEndPoint/get_dashboard_wallet
Content-Type: application/json

{ 
    "user_id": "5f69f307aaa0ae5497059482",
    "exchange": "binance"
}
###

POST app.digiebot.com/admin/trading_reports/Atg/find_available_btc_usdt_test
Content-Type: application/json

{ 
    "user_id": "5f69f307aaa0ae5497059482",
    "exchange": "binance",
    "baseCurrencyArr": ["BTC", "USDT"],
    "customBtcPackage": 0.02,
    "customUsdtPackage": 1000,
    "dailTradeAbleBalancePercentage": 10
}

###

GET http://localhost:3010/apiEndPoint/findCustomPackageVal

###


POST http://localhost:3010/apiEndPoint/isKeyUpdated
# POST http://34.205.124.51:3010/apiEndPoint/isKeyUpdated
Content-Type: application/json

{ 
    "user_id": "5c0912b7fc9aadaac61dd072",
    "exchange": "kraken"
}

###

POST http://localhost:3010/apiEndPoint/swap_kraken_api_keys
# POST http://34.205.124.51:3010/apiEndPoint/swap_kraken_api_keys
Content-Type: application/json

{ 
    
}

###

POST http://localhost:3010/apiEndPoint/updateDailyTradeSettings_digie_manual_run
###

GET http://localhost:3010/apiEndPoint/checkBnbMissingUsers


###

POST http://localhost:3010/apiEndPoint/hit_auto_buy_cron
# POST http://34.205.124.51:3010/apiEndPoint/hit_auto_buy_cron
Content-Type: application/json

{ 
    "user_id": "5c0912b7fc9aadaac61dd072",
    "exchange": "binance"   
}
